// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportHub.Data;

#nullable disable

namespace SportHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260622115901_AddMatchExtensions")]
    partial class AddMatchExtensions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportHub.Models.Entities.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourtID")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("UserID", "BookingDate");

                    b.HasIndex("CourtID", "BookingDate", "Status");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_Status", "Status IN ('Pending','Confirmed','Cancelled','Completed','NoShow')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.BookingSlot", b =>
                {
                    b.Property<int>("BookingSlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingSlotID"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<int>("SlotID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("BookingSlotID");

                    b.HasIndex("SlotID");

                    b.HasIndex("BookingID", "SlotID")
                        .IsUnique();

                    b.ToTable("BookingSlots", (string)null);
                });

            modelBuilder.Entity("SportHub.Models.Entities.ChatBookingProposal", b =>
                {
                    b.Property<int>("ProposalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProposalID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("date");

                    b.Property<int?>("CourtID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<decimal?>("EstimatedCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("MatchID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverID")
                        .HasColumnType("int");

                    b.Property<int>("SenderID")
                        .HasColumnType("int");

                    b.Property<string>("SplitMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProposalID");

                    b.HasIndex("CourtID");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("SenderID");

                    b.HasIndex("MatchID", "SenderID", "ReceiverID", "Status");

                    b.ToTable("ChatBookingProposals", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChatBookingProposals_SplitMode", "SplitMode IN ('Equal','HostPays')");

                            t.HasCheckConstraint("CK_ChatBookingProposals_Status", "Status IN ('Waiting','Accepted','Rejected','Booked')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.ChatMessage", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MatchCardJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverID")
                        .HasColumnType("int");

                    b.Property<int?>("ReplyToMessageID")
                        .HasColumnType("int");

                    b.Property<int>("SenderID")
                        .HasColumnType("int");

                    b.HasKey("MessageID");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("ReplyToMessageID");

                    b.HasIndex("SenderID");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("SportHub.Models.Entities.Court", b =>
                {
                    b.Property<int>("CourtID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourtID"));

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourtType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("MaxPlayers")
                        .HasColumnType("tinyint");

                    b.Property<int>("SportID")
                        .HasColumnType("int");

                    b.Property<string>("SurfaceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("CourtID");

                    b.HasIndex("VenueID");

                    b.HasIndex("SportID", "VenueID");

                    b.ToTable("Courts", (string)null);
                });

            modelBuilder.Entity("SportHub.Models.Entities.CourtImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourtID")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.HasKey("ImageID");

                    b.HasIndex("CourtID");

                    b.ToTable("CourtImages", (string)null);
                });

            modelBuilder.Entity("SportHub.Models.Entities.CourtOwner", b =>
                {
                    b.Property<int>("OwnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerID"));

                    b.Property<string>("BankAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("TaxCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OwnerID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("CourtOwners", (string)null);
                });

            modelBuilder.Entity("SportHub.Models.Entities.CourtVenue", b =>
                {
                    b.Property<int>("VenueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AmenityFood")
                        .HasColumnType("bit");

                    b.Property<bool>("AmenityLocker")
                        .HasColumnType("bit");

                    b.Property<bool>("AmenityParking")
                        .HasColumnType("bit");

                    b.Property<bool>("AmenityShower")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time");

                    b.Property<int>("OwnerID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VenueID");

                    b.HasIndex("OwnerID");

                    b.HasIndex("City", "District");

                    b.ToTable("CourtVenues", (string)null);
                });

            modelBuilder.Entity("SportHub.Models.Entities.Friendship", b =>
                {
                    b.Property<int>("FriendshipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FriendshipID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceiverID")
                        .HasColumnType("int");

                    b.Property<int>("SenderID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FriendshipID");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("SenderID");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("SportHub.Models.Entities.Match", b =>
                {
                    b.Property<int>("MatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchID"));

                    b.Property<int?>("BookingID")
                        .HasColumnType("int");

                    b.Property<int?>("CourtID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("CustomCourtAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomCourtName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CustomLatitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("CustomLongitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<decimal?>("CustomPriceVnd")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("DepositStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSplitFee")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("date");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("MaxParticipants")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ParentMatchId")
                        .HasColumnType("int");

                    b.Property<string>("RecurringDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecurringUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("RemainingFeeStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<string>("SkillRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SportID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MatchID");

                    b.HasIndex("BookingID");

                    b.HasIndex("CourtID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("ParentMatchId");

                    b.HasIndex("SportID");

                    b.HasIndex("Status", "MatchDate", "SportID");

                    b.ToTable("Matches", null, t =>
                        {
                            t.HasCheckConstraint("CK_Matches_DepositStatus", "DepositStatus IN ('NotPaid','Paid')");

                            t.HasCheckConstraint("CK_Matches_RemainingFeeStatus", "RemainingFeeStatus IN ('NotDue','Notified','Paid')");

                            t.HasCheckConstraint("CK_Matches_Status", "Status IN ('Open','Full','InProgress','Completed','Cancelled','PendingDeposit')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.MatchInteraction", b =>
                {
                    b.Property<int>("InteractionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InteractionID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("InteractionID");

                    b.HasIndex("UserID");

                    b.HasIndex("MatchID", "UserID", "Action");

                    b.ToTable("MatchInteractions", null, t =>
                        {
                            t.HasCheckConstraint("CK_MatchInteractions_Action", "Action IN ('View','Skip','Request')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.MatchParticipant", b =>
                {
                    b.Property<int>("ParticipantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantID"));

                    b.Property<string>("JoinStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PlayerFeeDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerFeeReceiptUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerFeeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamSide")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ParticipantID");

                    b.HasIndex("UserID");

                    b.HasIndex("MatchID", "UserID")
                        .IsUnique();

                    b.ToTable("MatchParticipants", null, t =>
                        {
                            t.HasCheckConstraint("CK_MatchParticipants_JoinStatus", "JoinStatus IN ('Pending','Approved','Accepted','Declined','Cancelled')");

                            t.HasCheckConstraint("CK_MatchParticipants_PlayerFeeStatus", "PlayerFeeStatus IS NULL OR PlayerFeeStatus IN ('AwaitingPayment','Paid','Expired')");

                            t.HasCheckConstraint("CK_MatchParticipants_TeamSide", "TeamSide IS NULL OR TeamSide IN ('A','B')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.MatchPayment", b =>
                {
                    b.Property<int>("MatchPaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchPaymentID"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchID")
                        .HasColumnType("int");

                    b.Property<int>("PayerUserID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReceiptUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransactionRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MatchPaymentID");

                    b.HasIndex("PayerUserID");

                    b.HasIndex("MatchID", "PaymentType", "Status");

                    b.ToTable("MatchPayments", null, t =>
                        {
                            t.HasCheckConstraint("CK_MatchPayments_Status", "Status IN ('Pending','Confirmed','Expired','Refunded')");

                            t.HasCheckConstraint("CK_MatchPayments_Type", "PaymentType IN ('HostDeposit','HostRemaining','PlayerFee')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.MatchReview", b =>
                {
                    b.Property<int>("MatchReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchReviewID"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("MatchID")
                        .HasColumnType("int");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ReviewedUserID")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerUserID")
                        .HasColumnType("int");

                    b.Property<byte?>("ScoreAtmosphere")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ScoreEquipment")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ScoreHost")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ScoreOrganization")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ScorePunctuality")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ScoreSkillAccuracy")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ScoreSportsmanship")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ScoreValueForMoney")
                        .HasColumnType("tinyint");

                    b.HasKey("MatchReviewID");

                    b.HasIndex("ReviewedUserID");

                    b.HasIndex("ReviewerUserID");

                    b.HasIndex("MatchID", "ReviewerUserID", "ReviewedUserID", "ReviewType")
                        .IsUnique();

                    b.ToTable("MatchReviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_MatchReviews_ScoreAtmos", "ScoreAtmosphere    IS NULL OR ScoreAtmosphere    BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_MatchReviews_ScoreEquip", "ScoreEquipment     IS NULL OR ScoreEquipment     BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_MatchReviews_ScoreHost", "ScoreHost          IS NULL OR ScoreHost          BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_MatchReviews_ScoreOrg", "ScoreOrganization  IS NULL OR ScoreOrganization  BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_MatchReviews_ScorePunct", "ScorePunctuality   IS NULL OR ScorePunctuality   BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_MatchReviews_ScoreSkill", "ScoreSkillAccuracy IS NULL OR ScoreSkillAccuracy BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_MatchReviews_ScoreSport", "ScoreSportsmanship IS NULL OR ScoreSportsmanship BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_MatchReviews_ScoreValue", "ScoreValueForMoney IS NULL OR ScoreValueForMoney BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_MatchReviews_Type", "ReviewType IN ('PlayerToMatch','HostToPlayer')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.MessageReaction", b =>
                {
                    b.Property<int>("ReactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReactionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MessageID")
                        .HasColumnType("int");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReactionID");

                    b.HasIndex("UserID");

                    b.HasIndex("MessageID", "UserID", "ReactionType")
                        .IsUnique();

                    b.ToTable("MessageReactions", (string)null);
                });

            modelBuilder.Entity("SportHub.Models.Entities.MessageReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiAnalysis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiRecommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AiViolationScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MessageID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReporterID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByAdminID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportID");

                    b.HasIndex("MessageID");

                    b.HasIndex("ReporterID");

                    b.HasIndex("ReviewedByAdminID");

                    b.ToTable("MessageReports", null, t =>
                        {
                            t.HasCheckConstraint("CK_MessageReports_Status", "Status IN ('Pending','Reviewed','Dismissed')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID", "IsRead");

                    b.ToTable("Notifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_Notifications_Type", "Type IN ('MatchJoin','MatchApprove','MatchReject','MatchJoinExpired','BookingConfirmed','BookingCancelled','System','Chat','MatchPaymentRequired','MatchRemainingFeeRequired','MatchPaymentConfirmed','MatchCompleted','MatchReviewReminder','RemainingFeeReminder','WalletCredit')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentID");

                    b.HasIndex("BookingID");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_PaymentMethod", "PaymentMethod IN ('VNPay','MoMo','ZaloPay','BankTransfer','Cash')");

                            t.HasCheckConstraint("CK_Payments_PaymentType", "PaymentType IN ('Payment','Refund')");

                            t.HasCheckConstraint("CK_Payments_Status", "Status IN ('Pending','Success','Failed','Refunded')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.PricingRule", b =>
                {
                    b.Property<int>("PricingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PricingID"));

                    b.Property<int>("CourtID")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SlotID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("PricingID");

                    b.HasIndex("SlotID");

                    b.HasIndex("CourtID", "SlotID", "DayType", "ValidFrom")
                        .IsUnique();

                    b.ToTable("PricingRules", null, t =>
                        {
                            t.HasCheckConstraint("CK_PricingRules_DayType", "DayType IN ('Weekday','Weekend','Holiday')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourtID")
                        .HasColumnType("int");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("CourtID");

                    b.HasIndex("UserID");

                    b.HasIndex("BookingID", "UserID")
                        .IsUnique();

                    b.ToTable("Reviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Rating", "Rating BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("SportHub.Models.Entities.Sport", b =>
                {
                    b.Property<int>("SportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SportID");

                    b.HasIndex("SportName")
                        .IsUnique();

                    b.ToTable("Sports", (string)null);
                });

            modelBuilder.Entity("SportHub.Models.Entities.SubscriptionOrder", b =>
                {
                    b.Property<int>("SubscriptionOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionOrderID"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransactionRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionOrderID");

                    b.HasIndex("TransactionRef")
                        .IsUnique();

                    b.HasIndex("UserID", "Status");

                    b.ToTable("SubscriptionOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_SubscriptionOrders_Status", "Status IN ('Pending','Confirmed','Expired')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanID"));

                    b.Property<bool>("CanFilterByDistance")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSeePhoneNumber")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAiSuggestions")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDetailedStats")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPlayerFeeExempt")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPriorityListing")
                        .HasColumnType("bit");

                    b.Property<bool>("HasVerifiedBadge")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MonthlyCreateLimit")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyJoinLimit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PriceAnnual")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PriceMonthly")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PriceQuarterly")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("PriorityScore")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("PlanID");

                    b.HasIndex("PlanKey")
                        .IsUnique();

                    b.ToTable("SubscriptionPlans", (string)null);

                    b.HasData(
                        new
                        {
                            PlanID = 1,
                            CanFilterByDistance = false,
                            CanSeePhoneNumber = false,
                            Description = "Dành cho người mới bắt đầu",
                            HasAiSuggestions = false,
                            HasDetailedStats = false,
                            HasPlayerFeeExempt = false,
                            HasPriorityListing = false,
                            HasVerifiedBadge = false,
                            IsActive = true,
                            MonthlyCreateLimit = 1,
                            MonthlyJoinLimit = 3,
                            Name = "Miễn phí",
                            PlanKey = "Free",
                            PriceAnnual = 0m,
                            PriceMonthly = 0m,
                            PriceQuarterly = 0m,
                            PriorityScore = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            PlanID = 2,
                            CanFilterByDistance = true,
                            CanSeePhoneNumber = true,
                            Description = "Cho người chơi thường xuyên",
                            HasAiSuggestions = false,
                            HasDetailedStats = false,
                            HasPlayerFeeExempt = false,
                            HasPriorityListing = false,
                            HasVerifiedBadge = false,
                            IsActive = true,
                            MonthlyCreateLimit = 3,
                            MonthlyJoinLimit = 10,
                            Name = "Starter",
                            PlanKey = "Starter",
                            PriceAnnual = 0m,
                            PriceMonthly = 39000m,
                            PriceQuarterly = 99000m,
                            PriorityScore = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            PlanID = 3,
                            CanFilterByDistance = true,
                            CanSeePhoneNumber = true,
                            Description = "Cho người chơi nghiêm túc",
                            HasAiSuggestions = true,
                            HasDetailedStats = true,
                            HasPlayerFeeExempt = false,
                            HasPriorityListing = true,
                            HasVerifiedBadge = false,
                            IsActive = true,
                            MonthlyCreateLimit = -1,
                            MonthlyJoinLimit = -1,
                            Name = "Pro",
                            PlanKey = "Pro",
                            PriceAnnual = 890000m,
                            PriceMonthly = 99000m,
                            PriceQuarterly = 249000m,
                            PriorityScore = 2,
                            SortOrder = 2
                        },
                        new
                        {
                            PlanID = 4,
                            CanFilterByDistance = true,
                            CanSeePhoneNumber = true,
                            Description = "Dành cho đội nhóm & tổ chức",
                            HasAiSuggestions = true,
                            HasDetailedStats = true,
                            HasPlayerFeeExempt = true,
                            HasPriorityListing = true,
                            HasVerifiedBadge = true,
                            IsActive = true,
                            MonthlyCreateLimit = -1,
                            MonthlyJoinLimit = -1,
                            Name = "Club",
                            PlanKey = "Club",
                            PriceAnnual = 0m,
                            PriceMonthly = 199000m,
                            PriceQuarterly = 499000m,
                            PriorityScore = 3,
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.SubscriptionUsage", b =>
                {
                    b.Property<int>("SubscriptionUsageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionUsageID"));

                    b.Property<int>("CreateCount")
                        .HasColumnType("int");

                    b.Property<int>("JoinCount")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SubscriptionUsageID");

                    b.HasIndex("UserID", "YearMonth")
                        .IsUnique();

                    b.ToTable("SubscriptionUsages", (string)null);
                });

            modelBuilder.Entity("SportHub.Models.Entities.TimeSlot", b =>
                {
                    b.Property<int>("SlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotID"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("SlotLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("SlotID");

                    b.HasIndex("StartTime", "EndTime")
                        .IsUnique();

                    b.ToTable("TimeSlots", (string)null);
                });

            modelBuilder.Entity("SportHub.Models.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BanEndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DefaultAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DefaultLatitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("DefaultLongitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FavoriteSport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int>("LoginCount")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WalletBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Gender", "Gender IN ('M','F','O')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.UserBadge", b =>
                {
                    b.Property<int>("BadgeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BadgeID"));

                    b.Property<string>("BadgeKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BadgeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgressValue")
                        .HasColumnType("int");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("BadgeID");

                    b.HasIndex("UserID", "BadgeKey")
                        .IsUnique();

                    b.ToTable("UserBadges", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserBadges_Level", "Level IN ('Bronze','Silver','Gold')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.UserBan", b =>
                {
                    b.Property<int>("BanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BanID"));

                    b.Property<string>("BanType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BannedByAdminID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("BanID");

                    b.HasIndex("BannedByAdminID");

                    b.HasIndex("ReportID");

                    b.HasIndex("UserID");

                    b.ToTable("UserBans", (string)null);
                });

            modelBuilder.Entity("SportHub.Models.Entities.UserMatchCredit", b =>
                {
                    b.Property<int>("UserMatchCreditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserMatchCreditID"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RemainingCredits")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransactionRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserMatchCreditID");

                    b.HasIndex("TransactionRef")
                        .IsUnique();

                    b.HasIndex("UserID", "Status");

                    b.ToTable("UserMatchCredits", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserMatchCredits_Status", "Status IN ('Pending','Confirmed')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.UserRole", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("SportHub.Models.Entities.UserSportProfile", b =>
                {
                    b.Property<int>("ProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileID"));

                    b.Property<string>("CourtPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SelfRatedLevel")
                        .HasColumnType("int");

                    b.Property<string>("SkillLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SportID")
                        .HasColumnType("int");

                    b.Property<string>("StrokeStrength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ProfileID");

                    b.HasIndex("SportID");

                    b.HasIndex("UserID", "SportID")
                        .IsUnique();

                    b.ToTable("UserSportProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_USP_CourtPosition", "CourtPosition  IS NULL OR CourtPosition  IN ('BackCourt','FrontCourt','AllRound')");

                            t.HasCheckConstraint("CK_USP_PlayStyle", "PlayStyle      IS NULL OR PlayStyle      IN ('Aggressive','Defensive','Balanced')");

                            t.HasCheckConstraint("CK_USP_SelfRated", "SelfRatedLevel IS NULL OR SelfRatedLevel BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_USP_StrokeStrength", "StrokeStrength IS NULL OR StrokeStrength IN ('Smash','Drop','Drive','AllRound')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.UserSubscription", b =>
                {
                    b.Property<int>("UserSubscriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSubscriptionID"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserSubscriptionID");

                    b.HasIndex("UserID", "Status");

                    b.ToTable("UserSubscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserSubscriptions_BillingCycle", "BillingCycle IN ('Monthly','Quarterly','Annual','Trial')");

                            t.HasCheckConstraint("CK_UserSubscriptions_Status", "Status IN ('Active','Expired','Cancelled')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.WalletTopUpRequest", b =>
                {
                    b.Property<int>("WalletTopUpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletTopUpID"));

                    b.Property<decimal?>("ActualAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransactionRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("WalletTopUpID");

                    b.HasIndex("TransactionRef")
                        .IsUnique();

                    b.HasIndex("UserID", "Status");

                    b.ToTable("WalletTopUpRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_WalletTopUpRequests_Status", "Status IN ('Pending','Confirmed','Expired')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.WalletTransaction", b =>
                {
                    b.Property<int>("WalletTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletTransactionID"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatedMatchID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("WalletTransactionID");

                    b.HasIndex("UserID");

                    b.ToTable("WalletTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_WalletTransactions_Type", "Type IN ('Refund','Deduction','AdminCredit','TopUp','MatchPayment')");
                        });
                });

            modelBuilder.Entity("SportHub.Models.Entities.Booking", b =>
                {
                    b.HasOne("SportHub.Models.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.BookingSlot", b =>
                {
                    b.HasOne("SportHub.Models.Entities.Booking", "Booking")
                        .WithMany("BookingSlots")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.TimeSlot", "TimeSlot")
                        .WithMany("BookingSlots")
                        .HasForeignKey("SlotID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("SportHub.Models.Entities.ChatBookingProposal", b =>
                {
                    b.HasOne("SportHub.Models.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SportHub.Models.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Match");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SportHub.Models.Entities.ChatMessage", b =>
                {
                    b.HasOne("SportHub.Models.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.ChatMessage", "ReplyToMessage")
                        .WithMany()
                        .HasForeignKey("ReplyToMessageID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SportHub.Models.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SportHub.Models.Entities.Court", b =>
                {
                    b.HasOne("SportHub.Models.Entities.Sport", "Sport")
                        .WithMany("Courts")
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.CourtVenue", "Venue")
                        .WithMany("Courts")
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sport");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("SportHub.Models.Entities.CourtImage", b =>
                {
                    b.HasOne("SportHub.Models.Entities.Court", "Court")
                        .WithMany("Images")
                        .HasForeignKey("CourtID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("SportHub.Models.Entities.CourtOwner", b =>
                {
                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithOne("CourtOwnerProfile")
                        .HasForeignKey("SportHub.Models.Entities.CourtOwner", "UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.CourtVenue", b =>
                {
                    b.HasOne("SportHub.Models.Entities.CourtOwner", "Owner")
                        .WithMany("Venues")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SportHub.Models.Entities.Friendship", b =>
                {
                    b.HasOne("SportHub.Models.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SportHub.Models.Entities.Match", b =>
                {
                    b.HasOne("SportHub.Models.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SportHub.Models.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SportHub.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.Match", "ParentMatch")
                        .WithMany("RecurringChildren")
                        .HasForeignKey("ParentMatchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SportHub.Models.Entities.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Court");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ParentMatch");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportHub.Models.Entities.MatchInteraction", b =>
                {
                    b.HasOne("SportHub.Models.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.MatchParticipant", b =>
                {
                    b.HasOne("SportHub.Models.Entities.Match", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.MatchPayment", b =>
                {
                    b.HasOne("SportHub.Models.Entities.Match", "Match")
                        .WithMany("MatchPayments")
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.User", "Payer")
                        .WithMany()
                        .HasForeignKey("PayerUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("SportHub.Models.Entities.MatchReview", b =>
                {
                    b.HasOne("SportHub.Models.Entities.Match", "Match")
                        .WithMany("Reviews")
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.User", "ReviewedUser")
                        .WithMany()
                        .HasForeignKey("ReviewedUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.User", "ReviewerUser")
                        .WithMany()
                        .HasForeignKey("ReviewerUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("ReviewedUser");

                    b.Navigation("ReviewerUser");
                });

            modelBuilder.Entity("SportHub.Models.Entities.MessageReaction", b =>
                {
                    b.HasOne("SportHub.Models.Entities.ChatMessage", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.MessageReport", b =>
                {
                    b.HasOne("SportHub.Models.Entities.ChatMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.User", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Message");

                    b.Navigation("Reporter");

                    b.Navigation("ReviewedByAdmin");
                });

            modelBuilder.Entity("SportHub.Models.Entities.Notification", b =>
                {
                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.Payment", b =>
                {
                    b.HasOne("SportHub.Models.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SportHub.Models.Entities.PricingRule", b =>
                {
                    b.HasOne("SportHub.Models.Entities.Court", "Court")
                        .WithMany("PricingRules")
                        .HasForeignKey("CourtID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.TimeSlot", "TimeSlot")
                        .WithMany("PricingRules")
                        .HasForeignKey("SlotID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("SportHub.Models.Entities.Review", b =>
                {
                    b.HasOne("SportHub.Models.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.Court", "Court")
                        .WithMany("Reviews")
                        .HasForeignKey("CourtID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Court");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.SubscriptionOrder", b =>
                {
                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.SubscriptionUsage", b =>
                {
                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.UserBadge", b =>
                {
                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.UserBan", b =>
                {
                    b.HasOne("SportHub.Models.Entities.User", "BannedByAdmin")
                        .WithMany()
                        .HasForeignKey("BannedByAdminID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.MessageReport", "Report")
                        .WithMany()
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BannedByAdmin");

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.UserMatchCredit", b =>
                {
                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.UserRole", b =>
                {
                    b.HasOne("SportHub.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.UserSportProfile", b =>
                {
                    b.HasOne("SportHub.Models.Entities.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.UserSubscription", b =>
                {
                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.WalletTopUpRequest", b =>
                {
                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.WalletTransaction", b =>
                {
                    b.HasOne("SportHub.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Models.Entities.Booking", b =>
                {
                    b.Navigation("BookingSlots");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SportHub.Models.Entities.ChatMessage", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("SportHub.Models.Entities.Court", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("PricingRules");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SportHub.Models.Entities.CourtOwner", b =>
                {
                    b.Navigation("Venues");
                });

            modelBuilder.Entity("SportHub.Models.Entities.CourtVenue", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("SportHub.Models.Entities.Match", b =>
                {
                    b.Navigation("MatchPayments");

                    b.Navigation("Participants");

                    b.Navigation("RecurringChildren");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SportHub.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SportHub.Models.Entities.Sport", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("SportHub.Models.Entities.TimeSlot", b =>
                {
                    b.Navigation("BookingSlots");

                    b.Navigation("PricingRules");
                });

            modelBuilder.Entity("SportHub.Models.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CourtOwnerProfile");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
